export const techs = {
  react: 'React',
  rn: 'React Native',
  redux: 'Redux',
  reduxForm: 'Redux Form',
  formik: 'Formik',
  echarts: 'Echarts',
  node: 'Nodejs',
  mui: 'Material UI',
  sc: 'Styled Components',
  lang: 'i18n',
  mobx: 'MobX',
  postgre: 'PostgreSQL',
  aws: 'AWS',
  handlebars: 'Handlebars',
  php: 'PHP/Symfony',
  rtk: 'Redux Toolkit',
  gMap: 'Google Maps',
  bootstrap: 'Bootstrap',
  mongo: 'MongoDB/mongoose',
  express: 'Express',
  expressSession: 'Express Session',
  scss: 'SCSS',
  ckeditor: 'CKEditor',
};
